### ISSUE TITLE
user.update

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend-coordination#67]

**Comment by FinnStutzenstein** [comment]
Note: payload changed: `is_committee` -> `is_physical_person`.

**Comment by jsangmeister** [comment]
How do you set the vote delegations and groups on a non-temporary user?

**Comment by jsangmeister** [comment]
> How do you set the vote delegations and groups on a non-temporary user?

(Maybe temporary) solution, similar to amendment_paragraphs:
```
{
    ...
    group_ids: {
        [meeting_id: Id]: Id[];
    };
    vote_delegations_from_ids: {
        [meeting_id: Id]: Id[];
    };
}
```

**Comment by FinnStutzenstein** [comment]
The group-ids solution will cause errors: E.g. if a user is in two meetings and one meetings blindly set just their ids, the ids of all other meetings will be removed.

**Comment by jsangmeister** [comment]
I don't think so: Assume `meeting/1` has `group/1` and `meeting/2` has `gorup/2`. `user/1` is currently in `group/1`, meaning its model looks like this:
```
{ ...
  group_$1_ids: [1],
  group_$_ids: ["1"],
... }
```
Now, `meeting/2` wants to assign the user to `group/2` and sends a request with `group_ids: [2]`. The backend will translate that to `group_$2_ids: [2]` (since `group/2` belongs to `meeting/2`). The automatic relation handling will update the field `group_$_ids` accordingly to `["1", "2"]`. `group_$1_ids` is never touched.

Looks right for me

**Comment by jsangmeister** [comment]
The one thing that is assumed here is that of one meeting, all group ids must be given, but thats the case for all similar update events.

**Comment by FinnStutzenstein** [comment]
Ah, this was not clear from the payload. So it behaves like this:

if there are group ids in `group_ids`, they must be from the same meeting. This will be set for the one meeting and other meetings are untouched, right? What happens, if `group_ids: []` is send to remove groups for one meeting?

**Comment by jsangmeister** [comment]
> they must be from the same meeting

No, you can provide groups from multiple meetings, but you must provide all groups from each meeting, because these will be set, overwriting, any old groups of that meeting.

> What happens, if `group_ids: []` is send to remove groups for one meeting?

Mmh. Currently, this is just ignored. I think I will have to revert it to my previous idea: handling it the same way as the vote delegations because with this "dynamic" approach I don't see a way to delete groups without an additional flag/field.

**Comment by FinnStutzenstein** [comment]
> Mmh. Currently, this is just ignored. I think I will have to revert it to my previous idea: handling it the same way as the vote delegations because with this "dynamic" approach I don't see a way to delete groups without an additional flag/field.

I lfavor this explicit way much more. Would be nice I think (The client can have just some special conversion before actually sending the data as a small hack, so it should be fine and is not a too large operation there.)

**Comment by FinnStutzenstein** [comment]
@jsangmeister This is the same problem as in https://github.com/OpenSlides/openslides-backend/issues/422

Can you do a concept for all these fields, so we can adjust the backend and client?

**Comment by jsangmeister** [comment]
Yes. In https://github.com/OpenSlides/openslides-backend/issues/170 we initially decided to not implement a generic solution, I guess this is obsolete now? :D

**Comment by jsangmeister** [comment]
Discussion continues in https://github.com/OpenSlides/openslides-backend/issues/422

**Comment by FinnStutzenstein** [comment]
To finish this up: We do have a generic solution now: Why? Since the cases where we need it grew, so a generic solution is preferable.
