### ISSUE TITLE
motion.set_support_self

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend-coordination#83]
Payload:

    {
        motion_id: Id;
        support: boolean;
    }

This adds (support=True) or removes (support=False) the request user from `motion/supporter_ids`. This action fails, if the supporter system is deactivated (`meeting/motions_supporters_min_amount==0`) or the motions state has `state/allow_support==False`.

**Comment by FinnStutzenstein** [comment]
This action is needed for unprivileged users: A user with only `can_see` may (un)support a motion, but he should not send an array of users. The backend (or perms service) must check, that the user just adds or removes him from the list. I've removed the `user_id` from the payload since this action is solely for the request user himself.

**Comment by jsangmeister** [comment]
Do we want to rename this to `set_support_self` to stay consistent in our naming conventions?

**Comment by reiterl** [comment]
Opened pull request https://github.com/OpenSlides/openslides-backend/pull/349 for this.
